package com.egoisticfoil.mneme.data

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.net.HttpURLConnection
import java.net.URI
import java.net.URL
import java.security.KeyStore
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import com.egoisticfoil.mneme.BuildConfig

enum class ThemePreference { Dark, Light, System }
enum class ColorPalette { Ocean, Forest, Lavender, Rose, Amber, Graphite }

data class AppSettings(
    val theme: ThemePreference = ThemePreference.Dark,
    val colorPalette: ColorPalette = ColorPalette.Ocean,
    val useMaterialYou: Boolean = false,
    val serverUrl: String = "",
    val serverToken: String = "",
    val serverConnected: Boolean = false,
    val serverVersion: String = "",
    val hasPin: Boolean = false,
    val appLockEnabled: Boolean = false,
    val biometricEnabled: Boolean = false,
)

class AppSettingsRepository(private val context: Context) {
    private val preferences = context.getSharedPreferences("mneme_settings", Context.MODE_PRIVATE)
    private val _settings = MutableStateFlow(load())
    val settings: StateFlow<AppSettings> = _settings.asStateFlow()

    fun setTheme(theme: ThemePreference) {
        preferences.edit().putString(KEY_THEME, theme.name).apply()
        _settings.value = _settings.value.copy(theme = theme)
    }

    fun setMaterialYou(enabled: Boolean) {
        preferences.edit().putBoolean(KEY_MATERIAL_YOU, enabled).apply()
        _settings.value = _settings.value.copy(useMaterialYou = enabled)
    }

    fun setColorPalette(palette: ColorPalette) {
        preferences.edit().putString(KEY_COLOR_PALETTE, palette.name).apply()
        _settings.value = _settings.value.copy(colorPalette = palette)
    }

    fun setPin(pin: String) {
        require(pin.length in 4..8 && pin.all(Char::isDigit)) { "Use a 4–8 digit PIN." }
        val salt = ByteArray(16).also { SecureRandom().nextBytes(it) }
        val hash = hashPin(pin, salt)
        preferences.edit()
            .putString(KEY_PIN_SALT, Base64.encodeToString(salt, Base64.NO_WRAP))
            .putString(KEY_PIN_HASH, Base64.encodeToString(hash, Base64.NO_WRAP))
            .putBoolean(KEY_APP_LOCK, true)
            .apply()
        _settings.value = _settings.value.copy(hasPin = true, appLockEnabled = true)
    }

    fun verifyPin(pin: String): Boolean {
        val salt = preferences.getString(KEY_PIN_SALT, null)?.let {
            runCatching { Base64.decode(it, Base64.NO_WRAP) }.getOrNull()
        } ?: return false
        val expected = preferences.getString(KEY_PIN_HASH, null)?.let {
            runCatching { Base64.decode(it, Base64.NO_WRAP) }.getOrNull()
        } ?: return false
        return MessageDigest.isEqual(expected, hashPin(pin, salt))
    }

    fun setAppLock(enabled: Boolean) {
        require(!enabled || _settings.value.hasPin) { "Set a PIN first." }
        preferences.edit().putBoolean(KEY_APP_LOCK, enabled).apply()
        if (!enabled) preferences.edit().putBoolean(KEY_BIOMETRIC, false).apply()
        _settings.value = _settings.value.copy(
            appLockEnabled = enabled,
            biometricEnabled = if (enabled) _settings.value.biometricEnabled else false,
        )
    }

    fun setBiometric(enabled: Boolean) {
        require(!enabled || _settings.value.appLockEnabled)
        preferences.edit().putBoolean(KEY_BIOMETRIC, enabled).apply()
        _settings.value = _settings.value.copy(biometricEnabled = enabled)
    }

    suspend fun connect(serverUrl: String, token: String): Result<Unit> = withContext(Dispatchers.IO) {
        runCatching {
            val normalizedUrl = normalizeServerUrl(serverUrl)
            require(token.isNotBlank()) { "Enter the token generated by your server." }
            val serverVersion = requestServerStatus(normalizedUrl, token.trim())

            preferences.edit()
                .putString(KEY_SERVER_URL, normalizedUrl)
                .putString(KEY_SERVER_TOKEN, encryptToken(token.trim()))
                .putBoolean(KEY_SERVER_CONNECTED, true)
                .putString(KEY_SERVER_VERSION, serverVersion)
                .apply()
            _settings.value = _settings.value.copy(
                serverUrl = normalizedUrl,
                serverToken = token.trim(),
                serverConnected = true,
                serverVersion = serverVersion,
            )
            BackupWorker.schedule(context)
            BackupWorker.scheduleSoon(context)
        }
    }

    suspend fun refreshServerVersion(): Result<String> = withContext(Dispatchers.IO) {
        runCatching {
            val current = settings.value
            require(current.serverConnected) { "Connect your Mneme server first." }
            val version = requestServerStatus(current.serverUrl, current.serverToken)
            preferences.edit().putString(KEY_SERVER_VERSION, version).apply()
            _settings.value = _settings.value.copy(serverVersion = version)
            version
        }
    }

    fun disconnectServer() {
        BackupWorker.cancel(context)
        preferences.edit()
            .remove(KEY_SERVER_URL)
            .remove(KEY_SERVER_TOKEN)
            .remove(KEY_SERVER_VERSION)
            .putBoolean(KEY_SERVER_CONNECTED, false)
            .apply()
        _settings.value = _settings.value.copy(
            serverUrl = "",
            serverToken = "",
            serverConnected = false,
            serverVersion = "",
        )
    }

    private fun load(): AppSettings = AppSettings(
        theme = preferences.getString(KEY_THEME, null)
            ?.let { stored -> ThemePreference.entries.firstOrNull { it.name == stored } }
            ?: ThemePreference.Dark,
        colorPalette = preferences.getString(KEY_COLOR_PALETTE, null)
            ?.let { stored -> ColorPalette.entries.firstOrNull { it.name == stored } }
            ?: ColorPalette.Ocean,
        useMaterialYou = preferences.getBoolean(KEY_MATERIAL_YOU, false),
        serverUrl = preferences.getString(KEY_SERVER_URL, "").orEmpty(),
        serverToken = preferences.getString(KEY_SERVER_TOKEN, null)
            ?.let(::decryptToken)
            .orEmpty(),
        serverConnected = preferences.getBoolean(KEY_SERVER_CONNECTED, false),
        serverVersion = preferences.getString(KEY_SERVER_VERSION, "").orEmpty(),
        hasPin = preferences.contains(KEY_PIN_HASH),
        appLockEnabled = preferences.getBoolean(KEY_APP_LOCK, false) && preferences.contains(KEY_PIN_HASH),
        biometricEnabled = preferences.getBoolean(KEY_BIOMETRIC, false),
    )

    private fun hashPin(pin: String, salt: ByteArray): ByteArray =
        SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
            .generateSecret(PBEKeySpec(pin.toCharArray(), salt, 150_000, 256))
            .encoded

    private fun normalizeServerUrl(value: String): String {
        val normalized = value.trim().trimEnd('/')
        val uri = runCatching { URI(normalized) }.getOrNull()
        val localDebugServer = BuildConfig.DEBUG && uri?.scheme == "http" &&
            uri.host in setOf("10.0.2.2", "127.0.0.1", "localhost")
        require((uri?.scheme == "https" || localDebugServer) && !uri.host.isNullOrBlank()) {
            "Enter an HTTPS server address (or 10.0.2.2 for local development)."
        }
        return normalized
    }

    private fun requestServerStatus(serverUrl: String, token: String): String {
        val connection = URL("$serverUrl/v1/vault/status").openConnection() as HttpURLConnection
        try {
            connection.requestMethod = "GET"
            connection.connectTimeout = 10_000
            connection.readTimeout = 10_000
            connection.setRequestProperty("Authorization", "Bearer $token")
            connection.setRequestProperty("Accept", "application/json")
            val responseCode = connection.responseCode
            if (responseCode == HttpURLConnection.HTTP_UNAUTHORIZED) error("The server rejected this token.")
            if (responseCode != HttpURLConnection.HTTP_OK) error("The server returned HTTP $responseCode.")
            val root = Json.parseToJsonElement(
                connection.inputStream.bufferedReader().use { it.readText() },
            ).jsonObject
            require(root["service"]?.jsonPrimitive?.content == "mneme") { "This URL is not a Mneme server." }
            return root["serverVersion"]?.jsonPrimitive?.content ?: "unknown"
        } finally {
            connection.disconnect()
        }
    }

    private fun encryptToken(token: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, tokenKey())
        val encrypted = cipher.doFinal(token.toByteArray(Charsets.UTF_8))
        return Base64.encodeToString(cipher.iv, Base64.NO_WRAP) + "." +
            Base64.encodeToString(encrypted, Base64.NO_WRAP)
    }

    private fun decryptToken(stored: String): String? = runCatching {
        val pieces = stored.split('.', limit = 2)
        require(pieces.size == 2)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            tokenKey(),
            GCMParameterSpec(128, Base64.decode(pieces[0], Base64.NO_WRAP)),
        )
        cipher.doFinal(Base64.decode(pieces[1], Base64.NO_WRAP)).toString(Charsets.UTF_8)
    }.getOrNull()

    private fun tokenKey(): SecretKey {
        val keyStore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore").run {
            init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(256)
                    .build(),
            )
            generateKey()
        }
    }

    private companion object {
        const val KEY_THEME = "theme"
        const val KEY_MATERIAL_YOU = "material_you"
        const val KEY_COLOR_PALETTE = "color_palette"
        const val KEY_SERVER_URL = "server_url"
        const val KEY_SERVER_TOKEN = "server_token"
        const val KEY_SERVER_CONNECTED = "server_connected"
        const val KEY_SERVER_VERSION = "server_version"
        const val KEY_ALIAS = "mneme_server_token"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_PIN_SALT = "pin_salt"
        const val KEY_PIN_HASH = "pin_hash"
        const val KEY_APP_LOCK = "app_lock"
        const val KEY_BIOMETRIC = "biometric"
    }
}
